#ifndef LANGUAGE_LPC
#define LANGUAGE_LPC
enum 
{
        L_LPC_LANG_NAME=1300,
		L_LPC_PLUGIN_NAME,
		L_LPC_STATUS_LABEL,
		L_LPC_STATUS_NAME_UNKNOWN,
		L_LPC_STATUS_NAME_CHECKING,
		L_LPC_STATUS_NAME_ERROR,
		L_LPC_STATUS_NAME_DISABLED,
		L_LPC_STATUS_NAME_LEVEL_HIGH,
		L_LPC_STATUS_NAME_LEVEL_MODERATE,
		L_LPC_STATUS_NAME_LEVEL_LOW,
		L_LPC_STATUS_NAME_LEVEL_MINIMAL,
		L_LPC_STATUS_NAME_LEVEL_NONE,
		L_LPC_CLICK,
};

#endif // LANGUAGE_LPC
