#ifndef LANGUAGE_WIRELESSEXPORT_H
#define LANGUAGE_WIRELESSEXPORT_H
enum
{
  L_WIRELESSEXPORT_BIGBT = 1600,
  L_WIRELESSEXPORT_LEFTBT,
//QGenieWelcomePage
  L_WIRELESSEXPORT_WELCOME_LB_TEXT,
  L_WIRELESSEXPORT_INTRODUCTION_LB_TEXT,
  L_WIRELESSEXPORT_OPT_PROMPT_LB_TEXT,
  L_WIRELESSEXPORT_NEXT_BTN_TEXT,
//QGenieWirelessPromptPage
  L_WIRELESSEXPORT_WPP_PREV_BTN_TEXT,
  L_WIRELESSEXPORT_WPP_NEXT_BTN_TEXT,
  L_WIRELESSEXPORT_WPP_CANCEL_BTN_TEXT,
  L_WIRELESSEXPORT_WPP_GETTING_WLAN_INFO,
  L_WIRELESSEXPORT_WPP_NO_WLAN_CONFIG,
  L_WIRELESSEXPORT_WPP_ADDDEVICE_2NETWORK,
//QGenieInsertFlashDiskPage
  L_WIRELESSEXPORT_FDP_PREV_BTN_TEXT,
  L_WIRELESSEXPORT_FDP_NEXT_BTN_TEXT,
  L_WIRELESSEXPORT_FDP_CANCEL_BTN_TEXT,
  L_WIRELESSEXPORT_FDP_OPTPROMPT_EXPORTING,
  L_WIRELESSEXPORT_FDP_OPTPROMPT_TRY_EXPORT_FAILED,
  L_WIRELESSEXPORT_FDP_OPTPROMPT_INSERT_FLASHDISK,
  L_WIRELESSEXPORT_FDP_OPTPROMPT_CLICK_NEXT,
//QGenieResultPage
  L_WIRELESSEXPORT_RP_FINISH_BTN_TEXT,
  L_WIRELESSEXPORT_RP_EXPORT_WLAN_OK,
  L_WIRELESSEXPORT_RP_EXPORT_WLAN_FAILED
};

#endif