#ifndef LANGUAGEGUESTACCESS_H
#define LANGUAGEGUESTACCESS_H

enum
{
    L_GUESTACCESS_BIGBT=1150,
    L_GUESTACCESS_ENABLEGUEST,
    L_GUESTACCESS_DISABLEGUEST,
    L_GUESTACCESS_GUESTWIRELESS_SSID,
    L_GUESTACCESS_WORKTIME,
    L_GUESTACCESS_SECURITYOPTIONS,
    L_GUESTACCESS_REFRESH,
    L_GUESTACCESS_APPLY,
    L_GUESTACCESS_CANCEL,
    L_GUESTACCESS_SECURITY,
    L_GUESTACCESS_PASSPHRASE,
    L_GUESTACCESS_PASS_LABLE,
    L_GUESTACCESS_BOX_TITLE,
    L_GUESTACCESS_BOX_MESSAGE,
    L_GUESTACCESS_BOX_2_TITLE,
    L_GUESTACCESS_BOX_2_MESSAGE,
    L_GUESTACCESS_BOX_3_TITLE,
    L_GUESTACCESS_BOX_3_MESSAGE,
    L_GUESTACCESS_BOX_4_TITLE,
    L_GUESTACCESS_BOX_4_MESSAGE,
    L_GUESTACCESS_BOX_5_TITLE,
    L_GUESTACCESS_BOX_5_MESSAGE,
    L_GUESTACCESS_BOX_6_TITLE,
    L_GUESTACCESS_BOX_6_MESSAGE,
    L_GUESTACCESS_BOX_OK,
    L_GUESTACCESS_BOX_CANCEL

};

#endif // LANGUAGEGUESTACCESS_H
