#ifndef LANGUAGE_NETTRAFFIC
#define LANGUAGE_NETTRAFFIC
enum 
{
        L_NETTRAFFIC_BIGBT=2000,
        L_NETTRAFFIC_LEFTBT,
        L_NETTRAFFIC_COLOR_SETTING,
        L_NETTRAFFIC_COLORS,
        L_NETTRAFFIC_GRAPH_COLORS,
        L_NETTRAFFIC_R_DATA,
        L_NETTRAFFIC_SENT_DATA,
        L_NETTRAFFIC_TOTAL_DATA,
        L_NETTRAFFIC_GRAPH_BACKGROUND,
        L_NETTRAFFIC_WINDOW_BACKGROUND,
        L_NETTRAFFIC_RESET_DEFAULTS,
        L_NETTRAFFIC_WINDOW_PROPERTIES,
        L_NETTRAFFIC_WINDOW_TRANSLUCENCY,
        L_NETTRAFFIC_OK,
        L_NETTRAFFIC_CANCEL,
        L_NETTRAFFIC_PROCTO,
        L_NETTRAFFIC_LOCAL_ADDRESS,
        L_NETTRAFFIC_REMOTE_ADDRESS,
        L_NETTRAFFIC_STATE,
        L_NETTRAFFIC_PROGRAM,
        L_NETTRAFFIC_REFRESH,
        L_NETTRAFFIC_CLOSE,
        L_NETTRAFFIC_DATA_UNITS,
        L_NETTRAFFIC_BITS,
        L_NETTRAFFIC_BYTES,
        L_NETTRAFFIC_SHOW_UNIT_OR_NOT,
        L_NETTRAFFIC_SHOW_UNIT,
        L_NETTRAFFIC_HIDE_UNIT,
        L_NETTRAFFIC_NETWORK_ADAPTERS,
        L_NETTRAFFIC_WHICH_MONITOR,
        L_NETTRAFFIC_TITLE_OPTION,
        L_NETTRAFFIC_TITLE_NETSTAT,
        L_NETTRAFFIC_MENU_NET_TRAFFIC,
        L_NETTRAFFIC_MENU_SWITCH_MODE,
        L_NETTRAFFIC_MENU_SWITCH_FONT,
        L_NETTRAFFIC_MENU_GENERAL_OPTIONS,
        L_NETTRAFFIC_MENU_GRAPH_COLOR,
        L_NETTRAFFIC_MENU_NETSTAT_LIST,
        L_NETTRAFFIC_ALERT_DISCON

};

#endif
