#ifndef  LANGUAGE_WIRELESS_H
#define LANGUAGE_WIRELESS_H
enum
{
  L_WIRELESS_BIGBT = 1100,
  L_WIRELESS_LEFTBT,
//  L_WIRELESS_STATUS_GOOD_LEFT,
  L_WIRELESS_STATUS_GOOD_RIGHT,
//  L_WIRELESS_STATUS_WARNNING_LEFT,
//  L_WIRELESS_STATUS_WARNNING_RIGHT,
 // L_WIRELESS_STATUS_ERROR_LEFT,
 // L_WIRELESS_STATUS_ERROR_RIGHT,
 // L_WIRELESS_STATUS_WAITING_LEFT,
  L_WIRELESS_STATUS_WAITING_RIGHT,
 // L_WIRELESS_STATUS_USER_LEFT,
  L_WIRELESS_STATUS_USER_RIGHT,
  L_WIRELESS_STATUS_USER2_LEFT,
  L_WIRELESS_STATUS_USER2_RIGHT,
  L_WIRELESS_OS_NOT_SUPPORT,
//QGenieWirelessTabWidget
  L_WIRELESS_WIRELESS_CHANNEL,
  L_WIRELESS_WIRELESS_CONNECT,
  L_WIRELESS_WIRELESS_GUESTACCESS,
//QGenieAvailableNetworkItem
  L_WIRELESS_ANI_CHANNEL_LB_TEXT,
  L_WIRELESS_ANI_CONNECTSTATE_CONNECTED,
  L_WIRELESS_ANI_CONNECTSTATE_LIMITEDCONNECT,
  L_WIRELESS_ANI_SECPROMPT_ENABLE_SEC,
  L_WIRELESS_ANI_SECPROMPT_DISABLE_SEC,
//QGenieInputPasswordWidget
  L_WIRELESS_IPW_OK_BTN_TEXT,
  L_WIRELESS_IPW_CANCEL_BTN_TEXT,
  L_WIRELESS_IPW_OPTRESULT_LB_TEXT,
  L_WIRELESS_IPW_PROMPT_LB_TEXT,
  L_WIRELESS_IPW_PLAINTEXT_CB_TEXT,
  L_WIRELESS_IPW_PWD_LB_TEXT,
  L_WIRELESS_IPW_DLG_TITLE,
  L_WIRELESS_IPW_PWDINVALID_PROMPT_TITLE,
  L_WIRELESS_IPW_PWDINVALID_PROMPT_TEXT,
//QGenieVisibleNetworkWidget
  L_WIRELESS_VNW_SELNETWORK_2CONNECT,
  L_WIRELESS_VNW_CONNECTING_NETWORK,
  L_WIRELESS_VNW_CONNECT2_NETWORK_FAILED,
  L_WIRELESS_VNW_REFRESHING_NETWORK,
  L_WIRElESS_VNW_REFRESHNETWORK_FAILED,
  L_WIRELESS_VNW_CONNECT_BTN_CONNECT,
  L_WIRELESS_VNW_CONNECT_BTN_DISCONNECT,
  L_WIRELESS_VNW_REFRESH_BTN_TEXT,
  L_WIRELESS_VNW_WND_TITLE,
  L_WIRELESS_VNW_MBOX_TITLE,
  L_WIRELESS_VNW_MBOX_SEL_NETWORK,
  L_WIRELESS_VNW_MBOX_BESURE_DISCONNECT,
  L_WIRELESS_VNW_MBOX_BESURE_CONNECT,
  L_WIRELESS_VNW_MBOX_PWD_INVALID,
  L_WIRELESS_VNW_MBOX_TITLE_ERROR,
  L_WIRELESS_VNM_MBOX_CONNECT_FAILED,
  L_WIRELESS_VNM_WZCAUTOCONF_DISABLED,
//QGenieCurChannelWidget
  L_WIRELESS_CCW_CHANNEL_LB_NOTNETGEARROUTER,
  L_WIRELESS_CCW_CHANNEL_LB_NOINFORMATION,
  L_WIRELESS_CCW_CHANNEL_LB_CURNETWORK,
  L_WIRELESS_CCW_CHANNEL_LB_CURCHANNEL,
  L_WIRELESS_CCW_PROMPT_LB_TEXT,
  L_WIRELESS_CCW_CHANNEL_LIST_ITEM0_TEXT,
  L_WIRELESS_CCW_REFRESH_BTN_TEXT,
  L_WIRELESS_CCW_CHANGECHANNEL_BTN_TEXT,
  L_WIRELESS_CCW_CHANNELLIST_CURRENTCHANNEL,
  L_WIRELESS_CCW_FREEZEUI_SECONDS,
//QGenieHistogramWidget
  L_WIRELESS_HW_Y_AXIS_LB_TEXT,
  L_WIRELESS_HW_X_AXIS_LB_TEXT,
//QGenieWirelessChannelView
  L_WIRELESS_WCV_CHANGECHANNEL_PROMPT_MBOX_TITLE,
  L_WIRELESS_WCV_CHANGECHANNEL_PROMPT_MBOX_TEXT,
  L_WIRELESS_WCV_CHANGECHANNEL_RESULT_MBOX_OK_TITLE,
  L_WIRELESS_WCV_CHANGECHANNEL_RESULT_MBOX_OK_TEXT,
  L_WIRELESS_WCV_CHANGECHANNEL_RESULT_MBOX_FAILED_TITLE,
  L_WIRELESS_WCV_CHANGECHANNEL_RESULT_MBOX_FAILED_TEXT,
  L_WIRELESS_WCV_CHANGECHANNEL_REQUEST_SUBMITTED_TEXT,
  L_WIRELESS_WCV_WIFI_LEGEND_TEXT,
  L_WIRELESS_WCV_WIFI_MYWIFI_TEXT,
  L_WIRELESS_WCV_WIFI_OTHERWIFI_TEXT,
  L_WIRELESS_WCV_WIFI_PROMPT_USER_TO_TOOLTIP_TEXT,
//QGenieInnerMsgBox
  L_WIRELESS_IMB_OK_TEXT,
  L_WIRELESS_IMB_YES_TEXT,
  L_WIRELESS_IMB_NO_TEXT,
 //QGenieColumnWidget
  L_WIRELESS_CW_COLUMN_TOOLTIP_TITLE
  

};
#endif
