#ifndef LANGUAGEROUTERCONFIGURATION_H
#define LANGUAGEROUTERCONFIGURATION_H

enum
{

L_RTCF_BIGBT=1500,
L_RTCF_BIGBT_CLICKHERE,

L_RTCF_LOGIN_TITLE,
L_RTCF_LOGIN_USER,
L_RTCF_PASSWORD,
L_RTCF_LOGIN_REMEMBER,
L_RTCF_LOGIN_BUT_LEFT,
L_RTCF_CANCEL,


L_RTCF_SETTING_SSID,
L_RTCF_SETTING_CHANNEL,
L_RTCF_SETTING_MODE,
L_RTCF_SETTING_SECURITY,

L_RTCF_SETTING_NOTE,
L_RTCF_SETTING_APPLY,

L_RTCF_IMSGBOX_OK,



L_RTCF_INFO_CHANNEL,
L_RTCF_INFO_CHOICE,
L_RTCF_INFO_PASSWOED,
L_RTCF_INFO_REFRESH,
L_RTCF_INFO_MODIFY,
L_RTCF_INFO_LOGINOUT,
L_RTCF_INFO_EXPORT,

L_RTCF_TAB_TITLE,


L_RTCF_MSG_NOTIFYCUT,
L_RTCF_MSG_NOTNETGEAR,
L_RTCF_MSG_PWDWRONG,
L_RTCF_MSG_LOGINTIMEOUT,
L_RTCT_MSG_PLEASEWAIT,
L_RTCT_MSG_COMMITWAIT,
L_RTCT_MSG_GACC,
L_RTCT_MSG_SOAPERROR,
L_RTCT_MSG_SOAPERROR_LOGIN,
L_RTCT_MSG_GACC_NOTSUPPORTED,
L_RTCF_MSG_TIMEOUT,
	
L_GACC_BIGBT,
L_GACC_ENABLEGUEST,
L_GACC_DISABLEGUEST,
L_GACC_ENABLE_TITLE,
L_GACC_ENABLED,
L_GACC_NOTENABLED,

L_GACC_GUESTWIRELESS_SSID,
L_GACC_WORKTIME,

L_RTCF_DEFAULT,
L_RTCF_LIST_TITLE,
L_RTCF_TRAFFICMETTER,
L_RTCF_FUPDATE,
L_RTCF_ROUTETYPE,
L_RTCF_FIRMWARE_VERSION,

L_RTCF_LOGIN_LIST,

L_GACC_ALWAYS,
L_GACC_1HOUR,
L_GACC_5HOUR,
L_GACC_10HOUR,
L_GACC_1DAY,
L_GACC_1WEEK
//language for ready share
,
L_READY_SHARE_BIGBT,
        L_READY_SHARE_DESC,     
        L_READY_SHARE_FUN_ONE,
        L_READY_SHARE_FUN_TWO,
        L_READY_SHARE_FUN_THREE,
        L_READY_SHARE_LIVE,
        L_READY_SHARE_BACK,
        L_READY_SHARE_CONTINUE,
        L_READY_SHARE_NOT_SUPPORT,
        L_READY_SHARE_SWITCH_TYPE,
        L_READY_SHARE_NETWORK_NAME,
        L_READY_SHARE_REGISTER,
        L_READY_SHARE_REMOTE,
        L_READY_SHARE_REMOTE_DESC,
        L_READY_SHARE_REMOTE_HOW_WORKS,
        L_READY_SHARE_REMOTE_STEPS_ONE,
        L_READY_SHARE_REMOTE_STEPS_TWO,
        L_READY_SHARE_REMOTE_STEPS_THREE,
        L_READY_SHARE_REMOTE_STEPS_FOUR,
        L_READY_SHARE_REMOTE_START_NOW,
        L_READY_SHARE_REMOTE_USERNAME,
        L_READY_SHARE_REMOTE_PASSWORD,
        L_READY_SHARE_REMOTE_GET_ACCOUNT,
        L_READY_SHARE_PRINTING,
        L_READY_SHARE_PRINTING_DESC,
        L_READY_SHARE_PRINTING_HOW_WORKS,
        L_READY_SHARE_PRINTING_STEPS_ONE,
        L_READY_SHARE_PRINTING_STEPS_TWO,
        L_READY_SHARE_PRINTING_STEPS_THREE,
        L_READY_SHARE_PRINTING_STEPS_FOUR,
        L_READY_SHARE_REMOTE_STEPS_NOTE,
        L_READY_SHARE_REMOTE_START_NOW_DESC,
        L_READY_SHARE_REMOTE_REGESTER_NOTE,
        L_READY_SHARE_REMOTE_REGESTER_USER,
        L_READY_SHARE_REMOTE_REGESTER_ANYWAY,
        L_READY_SHARE_REMOTE_REGESTER_DIFFERENT,
        L_READY_SHARE_UNREGISTER,
        L_READY_SHARE_TIMEOUT,
        L_READY_SHARE_INVALID_USER
//end



};

#endif // LANGUAGEROUTERCONFIGURATION_H
