#ifndef LANGUAGE_PARENTAL_CONTROL
#define LANGUAGE_PARENTAL_CONTROL
enum 
{
        L_PARENTAL_CONTROL_BIGBT=1300,
        L_PARENTAL_CONTROL_DESC,
        L_PARENTAL_CONTROL_MANAGER,
        L_PARENTAL_CONTROL_INSTALL,
        L_PARENTAL_CONTROL_ENABLE,
        L_PARENTAL_CONTROL_NOT_ENABLE,
        L_PARENTAL_CONTROL_FUN_ONE,
        L_PARENTAL_CONTROL_FUN_TWO,
        L_PARENTAL_CONTROL_FUN_THREE,
        L_PARENTAL_CONTROL_LIVE,
        L_PARENTAL_CONTROL_CLICKHERE
};

#endif
