#ifndef _LANGUAGE_TESTUI_
#define _LANGUAGE_TESTUI_
enum
{
    L_TESTUI_BIGBT=0,
    L_TESTUI_LEFTBT,
    L_TESTUI_TAB_LEFT,
    L_TESTUI_TAB_MID,
    L_TESTUI_TAB_RIGHT,
    L_TESTUI_COMMIT_BUT,
    L_TESTUI_MAINBUT,
    L_TESTUI_BTOWBUT,
    L_TESTUI_GOOD_LEFT,
    L_TESTUI_GOOD_RIGHT,
    L_WARRING_LEFT,
    L_WARRING_RIGHT
};


#endif
