#ifndef LANGUAGE_FEEDBACK
#define LANGUAGE_FEEDBACK
enum 
{
        L_FEEDBACK_BIGBT=1900,
        L_FEEDBACK_LABLE_FROM,
        L_FEEDBACK_LABLE_SUB,
        L_FEEDBACK_BTN_SEND,
        L_FEEDBACK_BTN_CLEAR,
        L_FEEDBACK_BTN_BACK,
        L_FEEDBACK_BTN_FINISHED,
        L_FEEDBACK_LABEL_WAIT,
        L_FEEDBACK_LABEL_ERR_MSG,
        L_FEEDBACK_LABEL_SUB_SUC,
        L_FEEDBACK_LABEL_ERR_NET,
        L_FEEDBACK_TXT_SUB,
        L_FEEDBACK_TXT_FEEDBACK,
        L_FEEDBACK_TXT_CLICK_HERE,
        L_FEEDBACK_LABEL_DESC
};

#endif
