#ifndef LANGUAGEFIRMWAREUPDATE_H
#define LANGUAGEFIRMWAREUPDATE_H


enum
{
    L_UPGRADE_MAIN_NAME=1950,
    L_UPGRADE_MAIN_FAILED,
    L_UPGRADE_MAIN_CLICK_HERE,
    L_UPGRADE_WIZARD_BACKBUT,
    L_UPGRADE_WIZARD_NEXTBUT,
    L_UPGRADE_WIZARD_NEXTBUT_FINISH,
    L_UPGRADE_WIZARD_CANCELBUT,
    L_UPGRADE_INTRO_TITLE,
    L_UPGRADE_INTRO_EXPLAIN,
    L_UPGRADE_NOTNETGEAR_TITLE,
    L_UPGRADE_NOTNETGEAR_EXPLAIN,
    L_UPGRADE_INTRO_WAIT,
    L_UPGRADE_INTRO_LASTESTTIMEOUT,
    L_UPGRADE_INTRO_LASTESTTIMEOUT_ERROR,
    L_UPGRADE_CHECK_TITLE,
    L_UPGRADE_CHECK_EXPLAIN,
    L_UPGRADE_CHECK_MODEL,
    L_UPGRADE_CHECK_NOWVERSION,
    L_UPGRADE_CHECK_NEWVERSION,
    L_UPGRADE_CHECK_ISLASTEST,
    L_UPGRADE_DOWNLOAD_TITLE,
    L_UPGRADE_DOWNLOAD_EXPLAIN,
    L_UPGRADE_DOWNLOAD_POPEXPLAIN,
    L_UPGRADE_DOWNLOAD_LEAVETIME,
    L_UPGRADE_FILESIZE_ERROR,
    L_UPGRADE_FILEMD5_ERROR,
    L_UPGRADE_COMPLETE_TITLE,
    L_UPGRADE_COMPLETE_EXPLAIN,
    L_UPGRADE_COMPLETE_PATH,
    L_UPGRADE_FINISH_TITLE,
    L_UPGRADE_FINISH_EXPLAIN,
    L_UPGRADE_FINISH_COPYBTN,
    L_UPGRADE_SUCCESS_TITLE,
};



#endif // LANGUAGEFIRMWAREUPDATE_H
