#ifndef ___LANGUAGE_FIRMWAREUPDATE_H___ 
#define ___LANGUAGE_FIRMWAREUPDATE_H___
#define L_UPGRADE_DOWNLOAD_LEAVETIME (1950)
#define L_UPGRADE_UPDATE_CANCEL (1951)
#define L_UPGRADE_UPDATE_PAGE_FINISH (1952)
#define L_UPGRADE_UPDATE_TITLE (1953)
#define L_UPGRADE_UPDATE_ALREADY_NEWEST (1954)
#define L_UPGRADE_UPDATE_PAGE_WRONG (1955)
#define L_UPGRADE_UPDATE_DOWNLOAD (1956)
#define L_UPGRADE_UPDATE_FINISH (1957)
#define L_UPGRADE_UPDATE_CHECK_DESP (1958)
#define L_UPGRADE_UPDATE_DOWN_FILE (1959)
#define L_UPGRADE_UPDATE_LINK (1960)
#define L_UPGRADE_UPDATE_NETWORK_ERROR (1961)
#endif
