#ifndef ___LANGUAGE_AIRPRINT_H___ 
#define ___LANGUAGE_AIRPRINT_H___
#define L_AIRPRINT_BIGBT (1750)
#define L_AIRPRINT_REFRESHBT (1751)
#define L_AIRPRINT_USAGEDESCRIPTIONFORMAT (1752)
#define L_AIRPRINT_USAGEDESCRIPTION (1753)
#define L_AIRPRINT_USAGEDESCRIPTIONSTEP1TITLE (1754)
#define L_AIRPRINT_USAGEDESCRIPTIONSTEP1 (1755)
#define L_AIRPRINT_USAGEDESCRIPTIONSTEP2TITLE (1756)
#define L_AIRPRINT_USAGEDESCRIPTIONSTEP2 (1757)
#define L_AIRPRINT_UNINSTALLEDITUNES (1758)
#define L_AIRPRINT_UNINSTALLEDADOBEREADER (1759)
#define L_AIRPRINT_ALLUNINSTALLEDAPP (1760)
#define L_AIRPRINT_ALLUNINSTALLEDAPP2 (1761)
#define L_AIRPRINT_ALLUNINSTALLEDAPP3 (1762)
#define L_AIRPRINT_REFRESHDESCRIPTION (1763)
#define L_AIRPRINT_RINTERLISTPAGETITLE (1764)
#endif
