#ifndef __CMD_DEFS___
#define __CMD_DEFS___
//for statistic plugin
enum COMMAND_DEF
{
    COMMAND_CLICK,
    COMMAND_REGMAXVALUE,
    COMMAND_REMEMBER_SEARCH,
    COMMAND_SAVE_SEARCHDATA,
    COMMAND_NOTIFYNETSTATE,
    COMMAND_NOTIFY_SUBSTATE,
    COMMAND_NOTIFYROUTETYPE,
    COMMAND_NOTIFYGATEWAY,
    COMMAND_GETPWD,
    COMMAND_NOTIFY_FUPDATE,
    COMMAND_CHANGECHANNEL,
    COMMAND_TURNTOGACC,
    COMMAND_TURNTOREADYSHARE,
    COMMAND_DEBUG,
    //to notify something
    INFO_NOTIFY_SSID_CHANGE0    ,
    INFO_NOTIFY_SSID_CHANGE     ,
    INFO_NOTIFY_MAC_CHANGE     ,
    INFO_NOTIFY_GATEWAY_CHANGE ,
    INFO_NOTIFY_INTERFACE_CHANGE ,
    INFO_NOTIFY_CHANNEL_CHANGE ,
    INFO_NOTIFY_REGION_CHANGE   ,
    INFO_NOTIFY_NEED_RECONNECT
};



#endif
