#ifndef __INFO_DEFS___
#define __INFO_DEFS___

#define LACK_PLUGIN "lackplugin"

//#define  "dependents"
//#define PLUGIN_INF_IS_NETGEAR "isnetgear"
//#define PLUGIN_INF_ROUTE_MAC "rmac"



typedef struct _TRAFFIC_ENTRY_
{
      double value;
      bool connected;
} TRAFFICENTRY;

enum PLUGIN_INFO_DEF
{
    PLUGIN_INF_DEPENDENCE,
PLUGIN_INF_ROUTE_PWD,
PLUGIN_INF_LANGUAGE_FILE,
PLUGIN_INF_INNER_LANGUAGE ,
PLUGIN_INF_CREATE_DATE ,

PLUGIN_INF_SM_TRAFFIC_STATS ,
PLUGIN_INF_SM_TRAFFIC_INCOMING ,
PLUGIN_INF_SM_TRAFFIC_OUTGOING ,
PLUGIN_INF_TEXT_UPLOAD ,
PLUGIN_INF_TEXT_DOWNLOAD ,


INFO_CMD_SHEET_PARENT ,
INFO_CMD_NETSTATUSE ,
INFO_CMD_MAIN_GEOMETRY ,

INFO_CMD_WIRELESS_OK ,



//use info plugin to process these
INFO_CMD_NETGEAR ,
INFO_CMD_NETGEAR_REFRESH ,
INFO_CMD_ROUTEMAC ,
INFO_CMD_FIRMWARE ,
INFO_CMD_ROUTE_TYPE ,
INFO_CMD_ROUTE_TYPE_IMMEDIATE ,
INFO_CMD_ROUTE_TYPE_IMMEDIATE_SHORT ,
INFO_CMD_RATROSHARELEVEL ,
INFO_CMD_FIRMWARE_IMMEDIATE ,
INFO_CMD_FIRMWARE_IMMEDIATE_SHORT ,
INFO_CMD_FUPDATE_PARA1 ,
INFO_CMD_FUPDATE_PARA2 ,
INFO_CMD_FUPDATE_PARA3 ,
INFO_CMD_NETGEAR_CURRENTSET ,
INFO_CMD_GATEWAY ,
INFO_CMD_INTERFACE ,
INFO_CMD_CHANNEL ,
INFO_CMD_REGION ,
INFO_CMD_ROUTE_WAITTIME ,
INFO_CMD_SSID_IS_THIS ,
INFO_CMD_GENIE_INFO ,
INFO_CMD_OS_INFO ,

INFO_CMD_ROUTECONFIG_LOGIN ,
INFO_CMD_ROUTECONFIG_LOGOUT,
INFO_CMD_ROUTECONFIG_LOGIN_OK ,
INFO_CMD_ROUTECONFIG_EXPORT_AUTHOR,
INTO_CMD_ROUTECONFIG_EXPORT_PASSWORD,
INFO_CMD_ROUTECONFIG_WAITSTR,
INFO_CMD_ROUTECONFIG_APPLYEND,

//use statistic plugin to process these
INFO_CMD_CLICK_COUNT ,


//route image names
INFO_CMD_ROUTE_NAME_B1 ,
INFO_CMD_ROUTE_NAME_B2 ,
INFO_CMD_ROUTE_NAME_B3 ,
INFO_CMD_ROUTE_NAME_NORMAL ,
INFO_CMD_ROUTE_NAME_SELECTED ,
INFO_CMD_ROUTE_NAME_OFFLINE ,

//note image name



//INFO_WIRELESS_STATE,
//INFO_INTERNET_STATE


};

#define INFO_GENIE_B1 ":/node/genie_b1.png"
#define INFO_GENIE_B2 ":/node/genie_b2.png"
#define INFO_GENIE_B3 ":/node/genie_b3.png"
#define INFO_INTERNET_B1 ":/node/internet_b1.png"
#define INFO_INTERNET_B2 ":/node/internet_b2.png"
#define INFO_INTERNET_B3 ":/node/internet_b3.png"


#endif
