#ifndef INTERFACE2_CMDS_H
#define INTERFACE2_CMDS_H
enum _IFACE2_CMDS
{
    I2CMD_UUID
    ,I2CMD_VERSIONNUMBER
    ,I2CMD_CREATE_MAINFRAME
    ,I2CMD_TIMETO_CREATEUI //create ui ,and subscrib message here
    ,I2CMD_REGISTER_UI //from plugin REGISTER_UI then send to ui plugin
    ,I2CMD_CREATEUI_END //only to ui plugin
    ,I2CMD_TIMETO_START
    ,I2CMD_UI_COMMAND //only to ui plugin
    ,I2CMD_LANGUAGE_CHANGE
    ,I2CMD_ABOUTTO_QUIT
    ,I2CMD_UI_ACTION //from ui plugin to other plugin when ui clicked
    ,I2CMD_UI_LOWER
    ,I2CMD_NOTIFY_MESSAGE
    ,I2CMD_STATISTICS
    ,I2CMD_REGISTER_DBG_UI
    ,I2CMD_LAYZYLOAD


    ,I2CMD_OTHER1
    ,I2CMD_OTHER2
    ,I2CMD_OTHER3
    ,I2CMD_NUM
};
enum _HANDLER_CMDS
{
    HCMD_UUID_IDX
    ,HCMD_CHECK_DIR
    ,HCMD_HOMEDIR_NAME
    ,HCMD_INIT_DBGMODLE
    ,HCMD_REGISTER_UI
    ,HCMD_LANGUAGE_CHANGE
    ,HCMD_GET_TEXT
    ,HCMD_TRANSLATE_LABEL
    ,HCMD_TRANSLATE_BUTTON
    ,HCMD_TRANSLATE_CHECKBOX
    ,HCMD_TRANSLATE_RADIOBUT //10
    ,HCMD_TELL_OTHERPLUGIN //from plugin ui
    ,HCMD_GET_SETTINGS
    ,HCMD_SET_SETTINGS
    ,HCMD_SUBSCRIB_MESSAGE
    ,HCMD_NOTIFY_MESSAGE
    ,HCMD_ASK_SUBSCRIBED_MESSAGE
    ,HCMD_LOG
    ,HCMD_IMAGE_NAME
    ,HCMD_LOADPLUGIN
    ,HCMD_EXIT
    ,HCMD_REGISTER_DBG_UI
    ,HCMD_NUM
};

enum _SUBSCRIBED_SUB_CMDS
{
    SCCMD_CURRENTSETTING
    ,SCCMD_ROUTER_MODEL
    ,SCCMD_LANGUAGE
    ,SCCMD_ROUTER_MAC
    
    ,SCCMD_CONNECTION_STATE
    ,SCCMD_SSID
    ,SCCMD_ROUTERCONFIG_BUSY
    ,SCCMD_FIRMWARE
    ,SCCMD_NUM
};

enum _UI_SUB_CMDS
{
    UICMD_BIGBUTTON_BUTLINE_CLICKHERE
    ,UICMD_BIGBUTTION_BUTLINE_ERROR
    ,UICMD_BIGBUTTION_BUTLINE_GOOD
    ,UICMD_BIGBUTTION_BUTLINE_OVERFLOW
    ,UICMD_BIGBUTTION_BUTLINE_FIXIT
    ,UICMD_BIGBUTTON_ICON
    ,UICMD_BIGBUTTON_LANGUAGE
    ,UICMD_LEFTBUTTON_LANGUAGE
    ,UICMD_SHOW_MAINFRAME
    ,UICMD_SET_FRAMELESS_STYLE
    ,UICMD_TRAY_ICO
    ,UICMD_TRAY_MESSAGE
    ,UICMD_TRAY_TOOLTIP
    ,UICMD_TITLE_SSID
    ,UICMD_CHECK_LEFTBUT
    ,UICMD_TITLE_UPDATE
    ,UICMD_DIALOG_MODAL
    ,UICMD_DIALOG_WARRING
    ,UICMD_UNLOCK_SMARTNETWORK
    ,UICMD_CLEAR_DIRTY_FOCUSFRAME_FOR_MACOS
    ,UICMD_NUM
};

#endif // INTERFACE2_CMDS_H
