#ifndef _SETTING_DEF2_H_____
#define _SETTING_DEF2_H_____
#define UPDATE_IP "update/update_addr"
#define UPDATE_DESP_FILE "update/desp"
#define UPDATE_PORT "update/update_port"
#define SUPDATE_RETRYTIME "update/sup_retry"
#define FUPDATE_RETRYTIME "update/fup_retry"
#define LAUNCH_HAVEUPDATE "launch/update"
#define AD_ADDR "AD/ad_addr"
#define AD_PORT "AD/ad_port"
#define AD_DESP_ADDR "AD/disp"
#define LANGUAGE_SETTING "language/lanidx"
#define PLUGIN_TRAFFIC_WARRING "plugin/traffic_warring"
#define PLUGIN_TRAFFIC_THRESHOLD "plugin/traffic_threshold"
#define PLUGIN_STATICS_IP "statistics/statics_addr"
#define PLUGIN_STATICS_PORT "statistics/statics_port"
#define PLUGIN_MAP_SHOWNOTIFY "plugin/map_notify"
#define PLUGIN_ROUTECONF_USER "plugin/routerconf_user"
#define PLUGIN_ROUTECONF_PWD "plugin/routeconf_pwd"
#define PLUGIN_SMARTNETWORK_USER "plugin/sm_usr"
#define PLUGIN_SMARTNETWORK_PWD "plugin/sm_pwd"
#define PLUGIN_ROUTER_MODEL "plugin/route_model"
#define PLUGIN_SMARTNETWROK_ISREMOTE "plugin/sm_isremote"
#define PLUGIN_SMARTNETWORK_UNLOCKED "plugin/sm_unlocked"
#define PLUGIN_SMARTNETWORK_SAVEPWD "plugin/sm_savepwd"
#define PLUGIN_SMARTNETWORK_CURCP "plugin/sm_curcp"
#define PLUGIN_SMARTNETWORK_SAVECPSECUR "plugin/sm_savecpsecure"
#define PLUGIN_ROUTECONF_SAVEPWD "plugin/routeconf_savepwd"
#define PLUGIN_STATICS_DISP "statistics/statics_disp"
#define PLUGIN_INTERNET_DETAIL "Internet/Details"
#define PLUGIN_AIRPRINT_PRINTERLIST "plugin/airprint_printerlist"
#define SOAP_SET_INTERVAL "soap/setInterval"
#define SOAP_GET_INTERVAL "soap/getInterval"
#define SHOW_NETWORK_CHANGE "plugin/shownetworkchange"
#define INSTALL_INFO_COMMITED "install_info/commited"
#define INSTALL_INFO_DATE "install_info/date"
#define INSTALL_INFO_TIME "install_info/time"
#define FOGOT_PWD_LINK "linkage/fogot"
#define SINGNUP_LINK "linkage/signup"
#define RSVALT_LINK "linkage/rsvalt"
#define SETTING_FCML_LINK "linkage/fcml"
#define APPSTORE_LINK "linkage/appstore"
#define MAP_USE_RDP "map/rdp"
#define MAP_USE_PUTTY "map/putty"

#ifdef Q_OS_MACX
#define MACOS_AUTOSTART "plugin/macos_autostart"
#endif
#define TITLE_URL "mainframe/title_url"
#endif
