#ifndef ___LANGUAGE_SMARTWIFI_H___
#define ___LANGUAGE_SMARTWIFI_H___
#define L_SMARTWIFI_BIGBT (1750)
#define L_SMARTWIFI_REFRESHBT (1751)
#define L_SMARTWIFI_USAGEDESCRIPTIONFORMAT (1752)
#define L_SMARTWIFI_USAGEDESCRIPTION (1753)
#define L_SMARTWIFI_USAGEDESCRIPTIONSTEP1TITLE (1754)
#define L_SMARTWIFI_USAGEDESCRIPTIONSTEP1 (1755)
#define L_SMARTWIFI_USAGEDESCRIPTIONSTEP2TITLE (1756)
#define L_SMARTWIFI_USAGEDESCRIPTIONSTEP2 (1757)
#define L_SMARTWIFI_UNINSTALLEDITUNES (1758)
#define L_SMARTWIFI_UNINSTALLEDADOBEREADER (1759)
#define L_SMARTWIFI_ALLUNINSTALLEDAPP (1760)
#define L_SMARTWIFI_ALLUNINSTALLEDAPP2 (1761)
#define L_SMARTWIFI_ALLUNINSTALLEDAPP3 (1762)
#define L_SMARTWIFI_REFRESHDESCRIPTION (1763)
#define L_SMARTWIFI_RINTERLISTPAGETITLE (1764)
#endif
