# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = lib
TARGET = ../../../../bin/ComputerDetails
DEFINES += _WINDOWS QT_DLL COMPUTERDETAILS_LIB _UNICODE  
HEADERS += ./GetDetails.h \
    ./computerdetails.h \
    ./computerdetails_global.h
SOURCES += ./GetDetails.cpp \
    ./computerdetails.cpp
