;* WARNING!  this file is generated by python scripts
;* WARNING!  All changes made in this file will be lost when re exec the python scripts!
;* any questions contact yidong.tao@dragonflow.com
!define VERSION "2.2.26.11 "
OutFile "NETGEARGenie-setup.exe"
	

